apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mission-db-pvc
  labels:
    app: mission-db
spec:
  selector:
    matchLabels:
      app: mission-db
  accessModes:
    - ReadWriteOnce
  storageClassName: mission-db-storage
  resources:
    requests:
      storage: 1Gi