apiVersion: v1
kind: Service
metadata:
  name: asset-service
  labels:
    app: asset-service
spec:
  selector:
    app: asset-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP