
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: quay.io/keycloak/keycloak:26.4.0
          imagePullPolicy: Always
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: auth-service-secrets
          volumeMounts:
            - name: keycloak-realm-volume
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: keycloak-realm-volume
          configMap:
            name: keycloak-realm-config