
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-service
  labels:
    app: mission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mission-service
  template:
    metadata:
      labels:
        app: mission-service
    spec:
      containers:
        - name: mission-service
          image: wadetyler/corsairops-mission-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: mission-service-secrets