apiVersion: v1
kind: Service
metadata:
  name: mission-service
  labels:
    app: mission-service
spec:
  selector:
    app: mission-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP