apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-db-pvc
  labels:
    app: asset-db
spec:
  selector:
    matchLabels:
      app: asset-db
  accessModes:
    - ReadWriteOnce
  storageClassName: asset-db-storage
  resources:
    requests:
      storage: 1Gi