apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  labels:
    app: maintenance-service
spec:
  selector:
    app: maintenance-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP