apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: auth-db-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-db-data
      volumes:
        - name: auth-db-data
          persistentVolumeClaim:
            claimName: auth-db-pvc