apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-pv
  labels:
    app: auth-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: auth-db-storage
  hostPath:
    path: /data/auth-db
  persistentVolumeReclaimPolicy: Retain