name: Reload on Push
on:
  push:
    branches: ["main"]

jobs:
  reload:
    name: Reload Deployment
    runs-on: self-hosted
    if: github.repository == 'CorsairOps/k8s'

    steps:
      - name: Perform Git Pull
        run: |
          cd ../corsairops/k8s
          git pull origin main

      - name: Reload Deployment
        run: |
          git pull origin main
          ./apply-secrets.sh
          for deployment in $(kubectl get deployments -n default -o custom-columns=NAME:.metadata.name --no-headers); do
            kubectl rollout restart deployment $deployment -n default
          done
          echo "All deployments reloaded successfully."